React to compiler analyzer warning/error
src\System.Private.Windows.Core\src\System\Private\Windows\Core\Nrbf\SerializationRecordExtensions.cs(352,74): error IDE0082: 'typeof' can be converted to 'nameof' (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0082) [D:\a\_work\1\vmr\src\winforms\src\System.Private.Windows.Core\src\System.Private.Windows.Core.csproj::TargetFramework=net10.0]