fix Error CS0579: Duplicate attribute
obj folders must be excluded from projects, otherwise they cause builds
to fail with similar errors:

  \winforms\artifacts\obj\InternalUtilitiesForTests\Debug\netcoreapp3.0\InternalUtilitiesForTests.AssemblyInfo.cs(14,12):
      Error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute
      Error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute
      Error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute
      Error CS0579: Duplicate 'System.Reflection.AssemblyInformationalVersionAttribute' attribute
      Error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute
      Error CS0579: Duplicate 'System.Reflection.AssemblyTitleAttribute' attribute
      Error CS0579: Duplicate 'System.Reflection.AssemblyVersionAttribute' attribute