Update machine requirements (#10982)
`Windows Media Player` and `Media Features` are required for building the full repo.

Without those Windows Features, the build fails with the following error:
```
C:\git\winforms\src\System.Windows.Forms\tests\AxHosts\AxHosts.Designer.cs(64,13): error CS0246: The type or namespace name 'AxWMPLib' could not be found (are you missing a using directive or an assembly reference?) [C:\git\winforms\src\System.Windows.Forms\tests\AxHosts\AxHosts.csproj] [C:\git\winforms\src\BuildAssist\BuildAssist.msbuildproj]
```